<a href="https://colab.research.google.com/github/paulorfbr/transformers_course/blob/tokenizer/Models_%26_Tokenizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install transformers

In [4]:
from transformers import AutoTokenizer

In [7]:
checkpoint = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [8]:
tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [13]:
tokens = tokenizer.tokenize("hello world")
tokens

['hello', 'world']

In [23]:
ids =  tokenizer.convert_tokens_to_ids(tokens)
ids

[7592, 2088]

In [24]:
tokenizer.decode(ids)

'hello world'

In [25]:
ids = tokenizer.encode("hello world")
ids

[101, 7592, 2088, 102]

In [26]:
tokens = tokenizer.convert_ids_to_tokens(ids)
tokens

['[CLS]', 'hello', 'world', '[SEP]']

In [29]:
from transformers import AutoModelForSequenceClassification

In [30]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [32]:
model_inputs = tokenizer("hello world", return_tensors="pt")
model_inputs

{'input_ids': tensor([[ 101, 7592, 2088,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [34]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.0010,  0.1539]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [35]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [36]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.1108,  0.2645,  0.5655]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [37]:
outputs.logits

tensor([[-0.1108,  0.2645,  0.5655]], grad_fn=<AddmmBackward0>)

In [38]:
outputs.logits.detach().cpu().numpy()

array([[-0.11075561,  0.26451963,  0.5655325 ]], dtype=float32)

In [39]:
data = [
    "I like cats",
    "Do you like cats too?"
]
model_inputs = tokenizer(data, padding=True, truncation=True, return_tensors="pt")
model_inputs

{'input_ids': tensor([[ 101, 1045, 2066, 8870,  102,    0,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])}

In [41]:
model_inputs['input_ids']

tensor([[ 101, 1045, 2066, 8870,  102,    0,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]])

In [42]:
model_inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])

In [43]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.2566,  0.2721,  0.5408],
        [-0.0170,  0.3199,  0.6351]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)